export const courses = [
    {
      id: 1,
      name: "Mesa de comedor moderno .",
      price: 29.99,
      description: "los conceptos básicos de JavaScript y desarrolla habilidades esenciales para programarAprende .",
      image: "https://disegnimobili.com.ar/wp-content/uploads/2020/03/00AEE73A-9325-41FD-9025-17F2181A7620_1_105_c.jpeg",
    },
    {
      id: 2,
      name: "Rack moderno",
      price: 49.99,
      description: "Domina React.js y aprende a crear aplicaciones web modernas y dinámicas con este curso práctico.",
      image: "https://i.pinimg.com/736x/fe/9f/50/fe9f5025e0dede036fbac7dad6ac3d97.jpg",
    },
    {
      id: 3,
      name: "Rack simple",
      price: 59.99,
      description: "Descubre cómo construir potentes APIs y servicios backend utilizando Node.js y Express.",
      image: "https://acdn.mitiendanube.com/stores/002/053/010/products/d_776441-mla29152420306_012019-o-209b929c79c23260ab17065646287713-240-0.jpg",
    },
    {
      id: 4,
      name: "Vanitori simple",
      price: 39.99,
      description: "Explora Python, uno de los lenguajes de programación más populares, con este curso interactivo.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHLANaTbwIGQ52UshHltYZF9KVFK_UFCv-xA&s",
    },
    {
      id: 5,
      name: "Vanitori modernoL",
      price: 45.99,
      description: "Aprende a diseñar, gestionar y consultar bases de datos relacionales con SQL.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQCQSE3fBl_-p9qSwCVEEVwiiVsxmGiq0ZWA&s",
    },
    {
      id: 6,
      name: "Juego dormitorio",
      price: 19.99,
      description: "Domina las bases del desarrollo web con este curso de HTML y CSS para principiantes.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw80mlavoNorkJOlcd_9QinW59ToRDhpGYZg&s",
    },
    {
      id: 7,
      name: "Placard moderno",
      price: 99.99,
      description: "Conviértete en un desarrollador full stack con conocimientos en frontend, backend y bases de datos.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHaY2cYmRf98WulkDqbOuZgNSbVYO48Lz4rw&s",
    },
  ];